[manager]
show_hidden = true
show_symlink = true

# widths for panes (out of 8)
ratio = [2, 3, 3]

[preview]
# \t character is 2 spaces long
tab_size = 2

[opener]
play = [
	{ run = 'mpv "$@"', orphan = true, for = "unix" },
]
view = [
	{ run = 'mpv "$@" --pause', for = "unix" }
]
open = [
	{ run = 'xdg-open "$@"', desc = "Open" },
]

[open]
prepend_rules = [
  { mime = "video/*", use = "play" },
	{ mime = "image/*", use = "view" },
	{ name = "*/", use = ["view"] }
]


