# sort out a plugin manager
source "$HOME/.config/zgen/zgen.zsh"

if ! zgen saved; then
  # add plugins
  zgen oh-my-zsh
  zgen oh-my-zsh plugins/git
  zgen oh-my-zsh plugins/git-extras
  zgen oh-my-zsh plugins/sudo

  zgen load zsh-users/zsh-completions src
  zgen load zsh-users/zsh-syntax-highlighting
  zgen load mafredri/zsh-async
  zgen load sindresorhus/pure

  zgen save
fi

ZGEN_RESET_ON_CHANGE=(${HOME}/.zshrc ${HOME}/.zshrc.local)

source "/usr/share/autojump/autojump.zsh"

alias sl="sl -l"
alias cat="ccat"
alias ttop="vtop"
alias clipboard="xclip -selection clipboard"
alias vim="nvim"
alias v="nvim"
alias nv="nvim"

eval "$(hub alias -s)"

# globbing
#setopt EXTENDED_GLOB    # use extended globbing
setopt GLOB_DOTS        # match patterns without leading dots
setopt NO_MATCH         # throw error if no match

# other options
setopt NO_CORRECT
setopt NO_BEEP

autoload -U compinit; compinit
# The following lines were added by compinstall

zstyle ':completion:*' completer _expand _complete _ignored _correct _approximate
zstyle :compinstall filename '/local/home/samson/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall
